[Titanic](https://www.kaggle.com/c/titanic/data)

# Project 1: Titanic

The sinking of the RMS Titanic is one of the most infamous shipwrecks in history.  On April 15, 1912, during her maiden voyage, the Titanic sank after colliding with an iceberg, killing 1502 out of 2224 passengers and crew. This sensational tragedy shocked the international community and led to better safety regulations for ships.

One of the reasons that the shipwreck led to such loss of life was that there were not enough lifeboats for the passengers and crew. Although there was some element of luck involved in surviving the sinking, some groups of people were more likely to survive than others, such as women, children, and the upper-class.

In this project, you will exercise your skills with loading data, python data structures, and Pandas to identify charactaristics of Titanic survivors!

### Considerations:

* You will be generating long data strutures- if you can, avoid displaying the whole thing. Display just the first or last few entries and look at the length or shape to check whether your code gives you back what you want and expect.
* Make functions whenever possiblle!
* Be explicit with your naming. You may forget what `this_list` is, but you will have an idea of what `passenger_fare_list` is. Variable naming will help you in the long run!
* Don't forget about tab autocomplete!
* Use markdown cells to document your planning, thoughts, and results. 
* Delete cells you will not include in your final submission
* Try to solve your own problems using this framework:
  1. Check your spelling
  2. Google your errors
  3. Ask your classmates
  4. Ask an instructor or TA

# 1. Using the `with open()` method in the `csv` library, load the titanic dataset into a list of lists.

* The `type()` of your dataset should be `list`
* The `type()` of each element in your dataset should also be `list`
* The `len()` of your dataset should be 892 (892 rows, including the header)
* The `len()` of each row element in your dataset should be have a `len()` of 12
* Print out the first 3 rows including the header to check your data.

In [1]:
import csv
from IPython.display import display
import numpy as np

In [2]:
dataset = []

with open('titanic.csv') as csvfile:
    my_reader = csv.reader(csvfile, delimiter=',')
    for row in my_reader:
        dataset.append(row)

In [3]:
len(dataset)

892

In [4]:
len(dataset[0])

12

In [5]:
dataset[:3]

[['PassengerId',
  'Survived',
  'Pclass',
  'Name',
  'Sex',
  'Age',
  'SibSp',
  'Parch',
  'Ticket',
  'Fare',
  'Cabin',
  'Embarked'],
 ['1',
  '0',
  '3',
  'Braund, Mr. Owen Harris',
  'male',
  '22',
  '1',
  '0',
  'A/5 21171',
  '7.25',
  '',
  'S'],
 ['2',
  '1',
  '1',
  'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'female',
  '38',
  '1',
  '0',
  'PC 17599',
  '71.2833',
  'C85',
  'C']]

# 2. Separate the first header row from the rest of your dataset. 

* The header should be a list of the column names
* The data should be the rest of your data
* Display the header and the first row of the dataset zipped together

In [6]:
header = dataset[0]
data = dataset[1:]

In [7]:
list(zip(header, data[0]))

[('PassengerId', '1'),
 ('Survived', '0'),
 ('Pclass', '3'),
 ('Name', 'Braund, Mr. Owen Harris'),
 ('Sex', 'male'),
 ('Age', '22'),
 ('SibSp', '1'),
 ('Parch', '0'),
 ('Ticket', 'A/5 21171'),
 ('Fare', '7.25'),
 ('Cabin', ''),
 ('Embarked', 'S')]

# 3. Using a `for` loop, load your data into a `dict` called `data_dict`.

* The keys of your `data_dict` should be `PassengerId`
* The values of your `data_dict` should be dictionaries...
  * Each of these dictionaries should reperesent a column value within a row
  * The keys should be the names of the columns
  * The values should be the values of that column
  
The beginning of your `data_dict` should look like: 

    {'1': {'Age': '22',
      'Cabin': '',
      'Embarked': 'S',
      'Fare': '7.25',
      'Name': 'Braund, Mr. Owen Harris',
      'Parch': '0',
      'Pclass': '3',
      'Sex': 'male',
      'SibSp': '1',
      'Survived': '0',
      'Ticket': 'A/5 21171'},
     '10': {'Age': '14',
      'Cabin': '',
      'Embarked': 'C',
      'Fare': '30.0708',
      'Name': 'Nasser, Mrs. Nicholas (Adele Achem)',
      'Parch': '0',
      'Pclass': '2',
      'Sex': 'female',
      'SibSp': '1',
      'Survived': '1',
      'Ticket': '237736'},
      ...
      }

In [8]:
data_dict = {}

for row in data:
    zipped = zip(header, row)
    row_dict = {}
    for col, element in zipped[1:]:
        row_dict[col] = element
    data_dict[row[0]] = row_dict

In [9]:
data_dict

{'1': {'Age': '22',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.25',
  'Name': 'Braund, Mr. Owen Harris',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '1',
  'Survived': '0',
  'Ticket': 'A/5 21171'},
 '10': {'Age': '14',
  'Cabin': '',
  'Embarked': 'C',
  'Fare': '30.0708',
  'Name': 'Nasser, Mrs. Nicholas (Adele Achem)',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'female',
  'SibSp': '1',
  'Survived': '1',
  'Ticket': '237736'},
 '100': {'Age': '34',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '26',
  'Name': 'Kantor, Mr. Sinai',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'male',
  'SibSp': '1',
  'Survived': '0',
  'Ticket': '244367'},
 '101': {'Age': '28',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.8958',
  'Name': 'Petranec, Miss. Matilda',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '349245'},
 '102': {'Age': '',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.8958',
  'Name': 'Petroff, Mr. Pastcho ("Pentcho")',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '349215'},
 '103': {'Age': '21',
  'Cabin': 'D26',
  'Embarked': 'S',
  'Fare': '77.2875',
  'Name': 'White, Mr. Richard Frasar',
  'Parch': '1',
  'Pclass': '1',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '35281'},
 '104': {'Age': '33',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '8.6542',
  'Name': 'Johansson, Mr. Gustaf Joel',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '7540'},
 '105': {'Age': '37',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.925',
  'Name': 'Gustafsson, Mr. Anders Vilhelm',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '2',
  'Survived': '0',
  'Ticket': '3101276'},
 '106': {'Age': '28',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.8958',
  'Name': 'Mionoff, Mr. Stoytcho',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '349207'},
 '107': {'Age': '21',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.65',
  'Name': 'Salkjelsvik, Miss. Anna Kristine',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '1',
  'Ticket': '343120'},
 '108': {'Age': '',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.775',
  'Name': 'Moss, Mr. Albert Johan',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '1',
  'Ticket': '312991'},
 '109': {'Age': '38',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.8958',
  'Name': 'Rekic, Mr. Tido',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '349249'},
 '11': {'Age': '4',
  'Cabin': 'G6',
  'Embarked': 'S',
  'Fare': '16.7',
  'Name': 'Sandstrom, Miss. Marguerite Rut',
  'Parch': '1',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '1',
  'Survived': '1',
  'Ticket': 'PP 9549'},
 '110': {'Age': '',
  'Cabin': '',
  'Embarked': 'Q',
  'Fare': '24.15',
  'Name': 'Moran, Miss. Bertha',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '1',
  'Survived': '1',
  'Ticket': '371110'},
 '111': {'Age': '47',
  'Cabin': 'C110',
  'Embarked': 'S',
  'Fare': '52',
  'Name': 'Porter, Mr. Walter Chamberlain',
  'Parch': '0',
  'Pclass': '1',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '110465'},
 '112': {'Age': '14.5',
  'Cabin': '',
  'Embarked': 'C',
  'Fare': '14.4542',
  'Name': 'Zabour, Miss. Hileni',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '1',
  'Survived': '0',
  'Ticket': '2665'},
 '113': {'Age': '22',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '8.05',
  'Name': 'Barton, Mr. David John',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '324669'},
 '114': {'Age': '20',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '9.825',
  'Name': 'Jussila, Miss. Katriina',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '1',
  'Survived': '0',
  'Ticket': '4136'},
 '115': {'Age': '17',
  'Cabin': '',
  'Embarked': 'C',
  'Fare': '14.4583',
  'Name': 'Attalah, Miss. Malake',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '2627'},
 '116': {'Age': '21',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.925',
  'Name': 'Pekoniemi, Mr. Edvard',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'STON/O 2. 3101294'},
 '117': {'Age': '70.5',
  'Cabin': '',
  'Embarked': 'Q',
  'Fare': '7.75',
  'Name': 'Connors, Mr. Patrick',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '370369'},
 '118': {'Age': '29',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '21',
  'Name': 'Turpin, Mr. William John Robert',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'male',
  'SibSp': '1',
  'Survived': '0',
  'Ticket': '11668'},
 '119': {'Age': '24',
  'Cabin': 'B58 B60',
  'Embarked': 'C',
  'Fare': '247.5208',
  'Name': 'Baxter, Mr. Quigg Edmond',
  'Parch': '1',
  'Pclass': '1',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'PC 17558'},
 '12': {'Age': '58',
  'Cabin': 'C103',
  'Embarked': 'S',
  'Fare': '26.55',
  'Name': 'Bonnell, Miss. Elizabeth',
  'Parch': '0',
  'Pclass': '1',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '1',
  'Ticket': '113783'},
 '120': {'Age': '2',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '31.275',
  'Name': 'Andersson, Miss. Ellis Anna Maria',
  'Parch': '2',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '4',
  'Survived': '0',
  'Ticket': '347082'},
 '121': {'Age': '21',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '73.5',
  'Name': 'Hickman, Mr. Stanley George',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'male',
  'SibSp': '2',
  'Survived': '0',
  'Ticket': 'S.O.C. 14879'},
 '122': {'Age': '',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '8.05',
  'Name': 'Moore, Mr. Leonard Charles',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'A4. 54510'},
 '123': {'Age': '32.5',
  'Cabin': '',
  'Embarked': 'C',
  'Fare': '30.0708',
  'Name': 'Nasser, Mr. Nicholas',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'male',
  'SibSp': '1',
  'Survived': '0',
  'Ticket': '237736'},
 '124': {'Age': '32.5',
  'Cabin': 'E101',
  'Embarked': 'S',
  'Fare': '13',
  'Name': 'Webber, Miss. Susan',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '1',
  'Ticket': '27267'},
 '125': {'Age': '54',
  'Cabin': 'D26',
  'Embarked': 'S',
  'Fare': '77.2875',
  'Name': 'White, Mr. Percival Wayland',
  'Parch': '1',
  'Pclass': '1',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '35281'},
 '126': {'Age': '12',
  'Cabin': '',
  'Embarked': 'C',
  'Fare': '11.2417',
  'Name': 'Nicola-Yarred, Master. Elias',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '1',
  'Survived': '1',
  'Ticket': '2651'},
 '127': {'Age': '',
  'Cabin': '',
  'Embarked': 'Q',
  'Fare': '7.75',
  'Name': 'McMahon, Mr. Martin',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '370372'},
 '128': {'Age': '24',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.1417',
  'Name': 'Madsen, Mr. Fridtjof Arne',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '1',
  'Ticket': 'C 17369'},
 '129': {'Age': '',
  'Cabin': 'F E69',
  'Embarked': 'C',
  'Fare': '22.3583',
  'Name': 'Peter, Miss. Anna',
  'Parch': '1',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '1',
  'Survived': '1',
  'Ticket': '2668'},
 '13': {'Age': '20',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '8.05',
  'Name': 'Saundercock, Mr. William Henry',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'A/5. 2151'},
 '130': {'Age': '45',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '6.975',
  'Name': 'Ekstrom, Mr. Johan',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '347061'},
 '131': {'Age': '33',
  'Cabin': '',
  'Embarked': 'C',
  'Fare': '7.8958',
  'Name': 'Drazenoic, Mr. Jozef',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '349241'},
 '132': {'Age': '20',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.05',
  'Name': 'Coelho, Mr. Domingos Fernandeo',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'SOTON/O.Q. 3101307'},
 '133': {'Age': '47',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '14.5',
  'Name': 'Robins, Mrs. Alexander A (Grace Charity Laury)',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '1',
  'Survived': '0',
  'Ticket': 'A/5. 3337'},
 '134': {'Age': '29',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '26',
  'Name': 'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'female',
  'SibSp': '1',
  'Survived': '1',
  'Ticket': '228414'},
 '135': {'Age': '25',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '13',
  'Name': 'Sobey, Mr. Samuel James Hayden',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'C.A. 29178'},
 '136': {'Age': '23',
  'Cabin': '',
  'Embarked': 'C',
  'Fare': '15.0458',
  'Name': 'Richard, Mr. Emile',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'SC/PARIS 2133'},
 '137': {'Age': '19',
  'Cabin': 'D47',
  'Embarked': 'S',
  'Fare': '26.2833',
  'Name': 'Newsom, Miss. Helen Monypeny',
  'Parch': '2',
  'Pclass': '1',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '1',
  'Ticket': '11752'},
 '138': {'Age': '37',
  'Cabin': 'C123',
  'Embarked': 'S',
  'Fare': '53.1',
  'Name': 'Futrelle, Mr. Jacques Heath',
  'Parch': '0',
  'Pclass': '1',
  'Sex': 'male',
  'SibSp': '1',
  'Survived': '0',
  'Ticket': '113803'},
 '139': {'Age': '16',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '9.2167',
  'Name': 'Osen, Mr. Olaf Elon',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '7534'},
 '14': {'Age': '39',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '31.275',
  'Name': 'Andersson, Mr. Anders Johan',
  'Parch': '5',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '1',
  'Survived': '0',
  'Ticket': '347082'},
 '140': {'Age': '24',
  'Cabin': 'B86',
  'Embarked': 'C',
  'Fare': '79.2',
  'Name': 'Giglio, Mr. Victor',
  'Parch': '0',
  'Pclass': '1',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'PC 17593'},
 '141': {'Age': '',
  'Cabin': '',
  'Embarked': 'C',
  'Fare': '15.2458',
  'Name': 'Boulos, Mrs. Joseph (Sultana)',
  'Parch': '2',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '2678'},
 '142': {'Age': '22',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.75',
  'Name': 'Nysten, Miss. Anna Sofia',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '1',
  'Ticket': '347081'},
 '143': {'Age': '24',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '15.85',
  'Name': 'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '1',
  'Survived': '1',
  'Ticket': 'STON/O2. 3101279'},
 '144': {'Age': '19',
  'Cabin': '',
  'Embarked': 'Q',
  'Fare': '6.75',
  'Name': 'Burke, Mr. Jeremiah',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '365222'},
 '145': {'Age': '18',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '11.5',
  'Name': 'Andrew, Mr. Edgardo Samuel',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '231945'},
 '146': {'Age': '19',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '36.75',
  'Name': 'Nicholls, Mr. Joseph Charles',
  'Parch': '1',
  'Pclass': '2',
  'Sex': 'male',
  'SibSp': '1',
  'Survived': '0',
  'Ticket': 'C.A. 33112'},
 '147': {'Age': '27',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.7958',
  'Name': 'Andersson, Mr. August Edvard ("Wennerstrom")',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '1',
  'Ticket': '350043'},
 '148': {'Age': '9',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '34.375',
  'Name': 'Ford, Miss. Robina Maggie "Ruby"',
  'Parch': '2',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '2',
  'Survived': '0',
  'Ticket': 'W./C. 6608'},
 '149': {'Age': '36.5',
  'Cabin': 'F2',
  'Embarked': 'S',
  'Fare': '26',
  'Name': 'Navratil, Mr. Michel ("Louis M Hoffman")',
  'Parch': '2',
  'Pclass': '2',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '230080'},
 '15': {'Age': '14',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.8542',
  'Name': 'Vestrom, Miss. Hulda Amanda Adolfina',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '350406'},
 '150': {'Age': '42',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '13',
  'Name': 'Byles, Rev. Thomas Roussel Davids',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '244310'},
 '151': {'Age': '51',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '12.525',
  'Name': 'Bateman, Rev. Robert James',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'S.O.P. 1166'},
 '152': {'Age': '22',
  'Cabin': 'C2',
  'Embarked': 'S',
  'Fare': '66.6',
  'Name': 'Pears, Mrs. Thomas (Edith Wearne)',
  'Parch': '0',
  'Pclass': '1',
  'Sex': 'female',
  'SibSp': '1',
  'Survived': '1',
  'Ticket': '113776'},
 '153': {'Age': '55.5',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '8.05',
  'Name': 'Meo, Mr. Alfonzo',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'A.5. 11206'},
 '154': {'Age': '40.5',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '14.5',
  'Name': 'van Billiard, Mr. Austin Blyler',
  'Parch': '2',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'A/5. 851'},
 '155': {'Age': '',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.3125',
  'Name': 'Olsen, Mr. Ole Martin',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'Fa 265302'},
 '156': {'Age': '51',
  'Cabin': '',
  'Embarked': 'C',
  'Fare': '61.3792',
  'Name': 'Williams, Mr. Charles Duane',
  'Parch': '1',
  'Pclass': '1',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'PC 17597'},
 '157': {'Age': '16',
  'Cabin': '',
  'Embarked': 'Q',
  'Fare': '7.7333',
  'Name': 'Gilnagh, Miss. Katherine "Katie"',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '1',
  'Ticket': '35851'},
 '158': {'Age': '30',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '8.05',
  'Name': 'Corn, Mr. Harry',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'SOTON/OQ 392090'},
 '159': {'Age': '',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '8.6625',
  'Name': 'Smiljanic, Mr. Mile',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '315037'},
 '16': {'Age': '55',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '16',
  'Name': 'Hewlett, Mrs. (Mary D Kingcome) ',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '1',
  'Ticket': '248706'},
 '160': {'Age': '',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '69.55',
  'Name': 'Sage, Master. Thomas Henry',
  'Parch': '2',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '8',
  'Survived': '0',
  'Ticket': 'CA. 2343'},
 '161': {'Age': '44',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '16.1',
  'Name': 'Cribb, Mr. John Hatfield',
  'Parch': '1',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '371362'},
 '162': {'Age': '40',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '15.75',
  'Name': 'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)',
  'Parch': '0',
  'Pclass': '2',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '1',
  'Ticket': 'C.A. 33595'},
 '163': {'Age': '26',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.775',
  'Name': 'Bengtsson, Mr. John Viktor',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '347068'},
 '164': {'Age': '17',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '8.6625',
  'Name': 'Calic, Mr. Jovo',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '315093'},
 '165': {'Age': '1',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '39.6875',
  'Name': 'Panula, Master. Eino Viljami',
  'Parch': '1',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '4',
  'Survived': '0',
  'Ticket': '3101295'},
 '166': {'Age': '9',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '20.525',
  'Name': 'Goldsmith, Master. Frank John William "Frankie"',
  'Parch': '2',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '1',
  'Ticket': '363291'},
 '167': {'Age': '',
  'Cabin': 'E33',
  'Embarked': 'S',
  'Fare': '55',
  'Name': 'Chibnall, Mrs. (Edith Martha Bowerman)',
  'Parch': '1',
  'Pclass': '1',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '1',
  'Ticket': '113505'},
 '168': {'Age': '45',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '27.9',
  'Name': 'Skoog, Mrs. William (Anna Bernhardina Karlsson)',
  'Parch': '4',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '1',
  'Survived': '0',
  'Ticket': '347088'},
 '169': {'Age': '',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '25.925',
  'Name': 'Baumann, Mr. John D',
  'Parch': '0',
  'Pclass': '1',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'PC 17318'},
 '17': {'Age': '2',
  'Cabin': '',
  'Embarked': 'Q',
  'Fare': '29.125',
  'Name': 'Rice, Master. Eugene',
  'Parch': '1',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '4',
  'Survived': '0',
  'Ticket': '382652'},
 '170': {'Age': '28',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '56.4958',
  'Name': 'Ling, Mr. Lee',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '1601'},
 '171': {'Age': '61',
  'Cabin': 'B19',
  'Embarked': 'S',
  'Fare': '33.5',
  'Name': 'Van der hoef, Mr. Wyckoff',
  'Parch': '0',
  'Pclass': '1',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '111240'},
 '172': {'Age': '4',
  'Cabin': '',
  'Embarked': 'Q',
  'Fare': '29.125',
  'Name': 'Rice, Master. Arthur',
  'Parch': '1',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '4',
  'Survived': '0',
  'Ticket': '382652'},
 '173': {'Age': '1',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '11.1333',
  'Name': 'Johnson, Miss. Eleanor Ileen',
  'Parch': '1',
  'Pclass': '3',
  'Sex': 'female',
  'SibSp': '1',
  'Survived': '1',
  'Ticket': '347742'},
 '174': {'Age': '21',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.925',
  'Name': 'Sivola, Mr. Antti Wilhelm',
  'Parch': '0',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'STON/O 2. 3101280'},
 '175': {'Age': '56',
  'Cabin': 'A7',
  'Embarked': 'C',
  'Fare': '30.6958',
  'Name': 'Smith, Mr. James Clinch',
  'Parch': '0',
  'Pclass': '1',
  'Sex': 'male',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': '17764'},
 '176': {'Age': '18',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '7.8542',
  'Name': 'Klasen, Mr. Klas Albin',
  'Parch': '1',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '1',
  'Survived': '0',
  'Ticket': '350404'},
 '177': {'Age': '',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '25.4667',
  'Name': 'Lefebre, Master. Henry Forbes',
  'Parch': '1',
  'Pclass': '3',
  'Sex': 'male',
  'SibSp': '3',
  'Survived': '0',
  'Ticket': '4133'},
 '178': {'Age': '50',
  'Cabin': 'C49',
  'Embarked': 'C',
  'Fare': '28.7125',
  'Name': 'Isham, Miss. Ann Elizabeth',
  'Parch': '0',
  'Pclass': '1',
  'Sex': 'female',
  'SibSp': '0',
  'Survived': '0',
  'Ticket': 'PC 17595'},
 '179': {'Age': '30',
  'Cabin': '',
  'Embarked': 'S',
  'Fare': '13',
  'Name': 'Hale, Mr. Reginald',
  'Parch': '0',

# 4. Repeat step 3 using a dictionary comprehension.

* Using `==`, check if your `data_dict` from your `for` loop is the same as the one from your dictionary comprehension.

In [ ]:
data_dict_comp = {row[0]:{i:j for i,j in zip(header[1:], row[1:])} for row in data}

In [ ]:
data_dict == data_dict_comp

# 5. Transform your `data_dict` to be oriented by column and call it `data_dict_columns`

* Currently, our `data_dict` is oriented by row, indexed by `"PassengerId"`. 
* Transform your data so that the title of each row is a key, the values are of type `list` and represent column vectors.

If you display `data_dict_columns`, the beginning should look like...

    {'Age': ['25',
      '36',
      '24',
      '40',
      '45',
      '2',
      '24',
      '28',
      '33',
      '26',
      '39',
      ...

In [10]:
data_dict_columns = {}
for col in header:
    data_dict_columns[col] = []

for pass_id, row in data_dict.items():
    data_dict_columns['PassengerId'].append(pass_id)
    for col, value in row.items():
        data_dict_columns[col].append(value)

# 6. Data Types

What is the current `type` of each column? What do you think the data type of each column *should* be? The data types in Python are...

* `int`
* `float`
* `str`
* `bool`
* `tuple`
* `list`
* `dict`
* `set`

In a markdown cell, describe what each column represents and what the `type` of each value should be. **Extra:** If you want to be fancy, use a markdown table to display your results.

### Add link to markdown table syntax


|Column|Type|
|---|---|
|Fare|`float`|
|Name|`str`|
|Embarked|`str`|
|Age|`float`|
|Parch|`int`|
|Pclass|`int`|
|Sex|`str`|
|Survived|`int`|
|SibSp|`int`|
|PassengerId|`int`|
|Ticket|`str`|
|Cabin|`str`|

# 7. Transform each column to the appropriate type if needed.

Build a function called `transform_column` that takes arguments for a `data_dict`, `column_name`, and `datatype`, and use it to transofm the columns that need transformation.

**NOTE:** There are values in this dataset that cannot be directly cast to a numerical value. Use `if/then` or `try/except` statements to handle errors. 

**To help identify potential sources of errors, explore the `set` of values in each column.**

In [11]:
data_dict_columns.keys()

['Fare',
 'Name',
 'Embarked',
 'Age',
 'Parch',
 'Pclass',
 'Sex',
 'Survived',
 'SibSp',
 'PassengerId',
 'Ticket',
 'Cabin']

In [12]:
non_str_cols = ['Fare','Age','Parch','Pclass','Survived','SibSp','PassengerId']
type_list = [float, float, int, int, int, int, int]

In [13]:
set(data_dict_columns[non_str_cols[0]])

{'0',
 '10.1708',
 '10.4625',
 '10.5',
 '10.5167',
 '106.425',
 '108.9',
 '11.1333',
 '11.2417',
 '11.5',
 '110.8833',
 '113.275',
 '12',
 '12.275',
 '12.2875',
 '12.35',
 '12.475',
 '12.525',
 '12.65',
 '12.875',
 '120',
 '13',
 '13.4167',
 '13.5',
 '13.7917',
 '13.8583',
 '13.8625',
 '133.65',
 '134.5',
 '135.6333',
 '14',
 '14.1083',
 '14.4',
 '14.4542',
 '14.4583',
 '14.5',
 '146.5208',
 '15',
 '15.0458',
 '15.05',
 '15.1',
 '15.2458',
 '15.5',
 '15.55',
 '15.7417',
 '15.75',
 '15.85',
 '15.9',
 '151.55',
 '153.4625',
 '16',
 '16.1',
 '16.7',
 '164.8667',
 '17.4',
 '17.8',
 '18',
 '18.75',
 '18.7875',
 '19.2583',
 '19.5',
 '19.9667',
 '20.2125',
 '20.25',
 '20.525',
 '20.575',
 '21',
 '21.075',
 '21.6792',
 '211.3375',
 '211.5',
 '22.025',
 '22.3583',
 '22.525',
 '221.7792',
 '227.525',
 '23',
 '23.25',
 '23.45',
 '24',
 '24.15',
 '247.5208',
 '25.4667',
 '25.5875',
 '25.925',
 '25.9292',
 '26',
 '26.25',
 '26.2833',
 '26.2875',
 '26.3875',
 '26.55',
 '262.375',
 '263',
 '27',
 '27.7208',
 '27.75',
 '27.9',
 '28.5',
 '28.7125',
 '29',
 '29.125',
 '29.7',
 '30',
 '30.0708',
 '30.5',
 '30.6958',
 '31',
 '31.275',
 '31.3875',
 '32.3208',
 '32.5',
 '33',
 '33.5',
 '34.0208',
 '34.375',
 '34.6542',
 '35',
 '35.5',
 '36.75',
 '37.0042',
 '38.5',
 '39',
 '39.4',
 '39.6',
 '39.6875',
 '4.0125',
 '40.125',
 '41.5792',
 '42.4',
 '46.9',
 '47.1',
 '49.5',
 '49.5042',
 '5',
 '50',
 '50.4958',
 '51.4792',
 '51.8625',
 '512.3292',
 '52',
 '52.5542',
 '53.1',
 '55',
 '55.4417',
 '55.9',
 '56.4958',
 '56.9292',
 '57',
 '57.9792',
 '59.4',
 '6.2375',
 '6.4375',
 '6.45',
 '6.4958',
 '6.75',
 '6.8583',
 '6.95',
 '6.975',
 '61.175',
 '61.3792',
 '61.9792',
 '63.3583',
 '65',
 '66.6',
 '69.3',
 '69.55',
 '7.0458',
 '7.05',
 '7.0542',
 '7.125',
 '7.1417',
 '7.225',
 '7.2292',
 '7.25',
 '7.3125',
 '7.4958',
 '7.5208',
 '7.55',
 '7.6292',
 '7.65',
 '7.725',
 '7.7292',
 '7.7333',
 '7.7375',
 '7.7417',
 '7.75',
 '7.775',
 '7.7875',
 '7.7958',
 '7.8',
 '7.8292',
 '7.8542',
 '7.875',
 '7.8792',
 '7.8875',
 '7.8958',
 '7.925',
 '71',
 '71.2833',
 '73.5',
 '75.25',
 '76.2917',
 '76.7292',
 '77.2875',
 '77.9583',
 '78.2667',
 '78.85',
 '79.2',
 '79.65',
 '8.0292',
 '8.05',
 '8.1125',
 '8.1375',
 '8.1583',
 '8.3',
 '8.3625',
 '8.4042',
 '8.4333',
 '8.4583',
 '8.5167',
 '8.6542',
 '8.6625',
 '8.6833',
 '8.7125',
 '8.85',
 '80',
 '81.8583',
 '82.1708',
 '83.1583',
 '83.475',
 '86.5',
 '89.1042',
 '9',
 '9.2167',
 '9.225',
 '9.35',
 '9.475',
 '9.4833',
 '9.5',
 '9.5875',
 '9.825',
 '9.8375',
 '9.8417',
 '9.8458',
 '90',
 '91.0792',
 '93.5'}

In [14]:
def transform_column(data_dict, column, datatype):
    new_col = []
    for i in data_dict[column]:
        try:
            new_col.append(datatype(i))
        except:
            new_col.append(np.NaN)
    data_dict[column] = new_col
    return data_dict

In [15]:
for col, datatype in zip(non_str_cols, type_list):
    data_dict_columns = transform_column(data_dict_columns, col, datatype)

# 8. Build functions to calculate the mean, standard deviation (sample, not population), median, and mode of a list of ints or floats. 


If you filled any missing values with `np.NaN`, you may need to handle that in your functions (look up `np.isnan()`).


**Hint:** Mode is tricky. Start by building a function that counts the occurances of each value. You may also need to sort using a `key` with a `lambda function` inside. You may also find a `defaultdict` useful.

**Optional:** for Mode, return the mode value *and* the count of that value.

Mean

In [16]:
def this_mean(data_list):
    data_list = [float(i) for i in data_list if not np.isnan(i)]
    return sum(data_list)/len(data_list)

Standard Deviation

In [17]:
def this_std(data_list):
    data_list = [float(i) for i in data_list if not np.isnan(i)]
    df = len(data_list) - 1
    mean = this_mean(data_list)
    dev = sum([(i - mean)**2 for i in data_list])
    return (dev/df)**.5

Median

In [18]:
def this_median(data_list):
    data_list = [float(i) for i in data_list if not np.isnan(i)]
    data_list.sort()
    l = len(data_list)
    if l%2 == 1:
        ind = l/2
        return data_list[ind]
    else:
        ind1 = l//2
        ind2 = ind1+1
        return this_mean([data_list[ind1], data_list[ind2]])

Mode

In [19]:
from collections import defaultdict

In [20]:
def counter(data_list):
    '''
    Returns a dict with the values as keys and the counts of each value as the dict values.
    '''
    count_dict = defaultdict(int)
    for i in data_list:
        count_dict[i] += 1
    return dict(count_dict)

In [21]:
def this_mode(data_list):
    '''
    Returns the mode and the no. of occurances of that value.
    '''
    counts = counter(data_list).items()
    counts.sort(key = lambda x: x[1], reverse=True)
    value, count = counts[0]
    return value, count

# 9. Summary Statistics of Numerical Columns

For numerical columns, what is the mean, standard deviation, mean, and mode for that data? Which measure of central tendency is the most descriptive of each column? Why? Explain your answer in a markdown cell.

In [22]:
def get_sum_stats(data_col):
    for name, method in [('mean',this_mean), 
                         ('standard deviation',this_std), 
                         ('median', this_median),
                         ('mode', this_mode)
                        ]:
        print("{:20} : {}".format(name, method(data_col)))

In [23]:
for col in non_str_cols:
    print("Column: {}".format(col))
    get_sum_stats(data_dict_columns[col])
    print('\n')

Column: Fare
mean                 : 32.2042079686
standard deviation   : 49.6934285972
median               : 14.4542
mode                 : (8.05, 43)


Column: Age
mean                 : 29.6991176471
standard deviation   : 14.5264973323
median               : 28.0
mode                 : (nan, 177)


Column: Parch
mean                 : 0.381593714927
standard deviation   : 0.80605722113
median               : 0.0
mode                 : (0, 678)


Column: Pclass
mean                 : 2.30864197531
standard deviation   : 0.836071240977
median               : 3.0
mode                 : (3, 491)


Column: Survived
mean                 : 0.383838383838
standard deviation   : 0.486592454265
median               : 0.0
mode                 : (0, 549)


Column: SibSp
mean                 : 0.523007856341
standard deviation   : 1.10274343229
median               : 0.0
mode                 : (0, 608)


Column: PassengerId
mean                 : 446.0
standard deviation   : 257.353842015
median               : 446.0
mode                 : (1, 1)

#### Fare

Fare has a mean of 32 with a std of almost 50. Because the median is around 14 and the mode is 8, the data is skewed. Thus, the median is the most appropriate measure to describe this data.

#### Age

The mean and median of Age are close to each other, so the data is likely not heavily skewed. The mean is appropriate in this case.

#### Parch

The mode is descriptive here: 678 individuals out of our entire dataset traveled without parents or children.

#### SibSp

The mode is descriptive here: 608 individuals out of our entire dataset traveled without siblings or spouses.

#### PassengerId

No descriptive stastics are informative

#### Pclass

The mode is descriptive here. More than half the passengers are in class 3

#### Survived

The mean is important here. The mean is the frequentist probability of survival on the Titanic

# 10. Splitting the Data to Predicting Survival

For all the passengers in the dataset, the mean survival rate is around .38 (38% of the passengers survived). From our data, we may be able to profile who survived and who didn't!

Split the data by pclass. Does the class a passenger was in affect survivability? You can do this by:
* Creating a list of `True` and `False` values conditional on a column's value
* Taking the mean of the `Survived` column where those values are `True`

In [24]:
set(data_dict_columns['Pclass'])

{1, 2, 3}

In [25]:
pclass_1_mask = [True if i == 1 else False for i in data_dict_columns['Pclass']]
pclass_2_mask = [True if i == 2 else False for i in data_dict_columns['Pclass']]
pclass_3_mask = [True if i == 3 else False for i in data_dict_columns['Pclass']]

In [26]:
pclass_1_prob = this_mean([i for i,j in zip(data_dict_columns['Survived'],pclass_1_mask) if j])
pclass_2_prob = this_mean([i for i,j in zip(data_dict_columns['Survived'],pclass_2_mask) if j])
pclass_3_prob = this_mean([i for i,j in zip(data_dict_columns['Survived'],pclass_3_mask) if j])

In [27]:
display(pclass_1_prob)
display(pclass_2_prob)
display(pclass_3_prob)

0.6296296296296297

0.47282608695652173

0.24236252545824846

# 11. Independent Work

Use the techniques from step 10 to make different conditional splits in the `Survived` column. Can you find a combination of splits that maximizes the survival rate?

In [28]:
child_mask = [True if i < 6.0 else False for i in data_dict_columns['Age']]

female_mask = [True if i == 'female' else False for i in data_dict_columns['Sex']]

In [29]:
women_children_mask = [i&j for i,j in zip(child_mask, female_mask)]

In [30]:
women_children_prob = this_mean([i for i,j in zip(data_dict_columns['Survived'],women_children_mask) if j])

In [31]:
women_children_prob

0.7619047619047619

# 12. Pandas

### A: Load the titanic csv into a `DataFrame` using `pd.read_csv()`

In [32]:
import pandas as pd

In [33]:
titanic_df = pd.read_csv('titanic.csv')

### B: Display the first 5 rows, the last 4 rows, and a sample of 3 rows.

In [34]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [35]:
titanic_df.tail(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [36]:
titanic_df.sample(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
415,416,0,3,"Meek, Mrs. Thomas (Annie Louise Rowley)",female,NaN,0,0,343095,8.050,NaN,S
219,220,0,2,"Harris, Mr. Walter",male,30.0,0,0,W/C 14208,10.500,NaN,S
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.0,0,0,364516,12.475,NaN,S

### C: Create a row mask that is `True` when `Pclass == 3`. Use this to mask your `DataFrame`. Find the mean of the `Survived` column. Is it the same as what we calculated in part 10?

In [37]:
pclass3_mask = titanic_df['Pclass'] == 3

In [38]:
titanic_df[pclass3_mask]['Survived'].mean()

0.24236252545824846

### D: Using a `.groupby()`, what is the mean of the survival column grouped by `Pclass` and `Sex`. What are your observations?

In [39]:
titanic_df.groupby(['Pclass','Sex'])[['Survived']].mean()

               Survived
Pclass Sex
1      female  0.968085
       male    0.368852
2      female  0.921053
       male    0.157407
3      female  0.500000
       male    0.135447

### E: Survival Rate by Age Range:  `pd.cut()` takes two arguments: A `list`, `Series`, or `array`, and a list of bins. Create a new column in your `DataFrame` using `pd.cut()` that groups your ages into bins of 5 years. Then, use `.groupby()` to display the survival rate and count for each age group

In [40]:
titanic_df['age_group'] = pd.cut(titanic_df['Age'],range(0,81,5))

In [41]:
titanic_df.groupby(['age_group'])[['Survived']].agg(['mean','count'])

           Survived
               mean count
age_group
(0, 5]     0.704545    44
(5, 10]    0.350000    20
(10, 15]   0.578947    19
(15, 20]   0.343750    96
(20, 25]   0.344262   122
(25, 30]   0.388889   108
(30, 35]   0.465909    88
(35, 40]   0.417910    67
(40, 45]   0.361702    47
(45, 50]   0.410256    39
(50, 55]   0.416667    24
(55, 60]   0.388889    18
(60, 65]   0.285714    14
(65, 70]   0.000000     3
(70, 75]   0.000000     4
(75, 80]   1.000000     1

# 13. Write-up

Use markdown cells to answer the following questions:

1. What is the main difference between a list and a tuple?
2. Can you iterate over a dictionary? If so, how?
3. What is the term for a list or array of `True` and `False` values used to select certain rows or columns in a `DataFrame`?
4. If you have a continuous variable, when would the median be a better descriptor than the mean? Why?
5. Give a qualitative description of the survivors of the titanic based on the effects of your splits in the data on survival rate. Or, given a row, what columns would you look at to guess if they survived?

# 14. Evaluation

Please use markdown cells to submit your responses. 

1. What was easy for you in this project?
2. What was difficult?
3. Where did you make the most improvement?
4. Where would you like to improve?